# Generated by Django 3.2 on 2022-02-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=40, unique=True, verbose_name='openid')),
                ('session_key', models.CharField(max_length=40, verbose_name='session_key')),
            ],
        ),
    ]
