# Generated by Django 3.2 on 2022-02-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=40, verbose_name='openid')),
                ('content', models.CharField(max_length=1024, verbose_name='日记内容')),
            ],
        ),
    ]
