# Generated by Django 3.2 on 2022-02-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_diaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remark',
            field=models.CharField(max_length=50, null=True, verbose_name='备注'),
        ),
    ]
