# Generated by Django 3.2 on 2022-02-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_user_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaries',
            name='publish_time',
            field=models.DateTimeField(default='2022-02-03 20:47:19', verbose_name='发布时间'),
        ),
    ]
