# Generated by Django 3.2 on 2022-02-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_diaries_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaries',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
